version: '3.8'

services:
  mongo:
    image: mongo:4.2
    container_name: mongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  foroblog-app:
    build:
      context: ./Back-end/foro-blog
    container_name: foroblog-app
    image: inncursio/foroblog-app:latest  # Etiqueta para Docker Hub
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - nats
      - eventstore
    env_file:
      - ./Back-end/foro-blog/.env
    environment:
      - MONGO_URI=mongodb://admin:admin@mongoDB:27017/foroblog?authSource=admin
      - PORT=3000

  
  foroblog-frontend:
    build:
      context: ./Front-end/foroblog-frontend
    container_name: foroblog-frontend
    image: inncursio/foroblog-frontend:latest  # Etiqueta para Docker Hub
    ports:
      - "3001:3001"
    depends_on:
      - foroblog-app
    env_file:
      - ./Front-end/foroblog-frontend/.env
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - PORT=3001

  evento-service:
    build:
      context: ./Back-end/evento-service
    container_name: evento-service
    image: inncursio/evento-service:latest  # Etiqueta para Docker Hub
    ports:
      - "4000:4000"
    depends_on:
    - nats
    - eventstore
    env_file:
      - ./Back-end/evento-service/.env
    environment:
      - NATS_URI=nats://nats:4222
      - EVENTSTORE_URI=esdb://eventstore:2113?tls=false
      - PORT=4000

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      - NATS_SERVER_NAME=nats_server

  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_ALLOW_UNKNOWN_OPTIONS=true
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - eventstore_data:/var/lib/eventstore

volumes:
  mongo_data:
  eventstore_data:
